[package]
name = "term_art"
version = "0.1.0"
edition = "2021"

[dependencies]
alea = "0.2.2"
ansi-style = "1.2.1"
better-panic = "0.3.0"
cli-clipboard = "0.4.0"
crossterm = "0.27.0"
hashbrown = "0.14.5"
ratatui = "0.27.0"
# strum = "0.26.2"
